language: node_js
node_js:
  - "5.10.1"

branches:
  only:
    - master

before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install

cache:
  directories:
    - ./node_modules
    - ./vendor

script:
  - npm run test