language: node_js
node_js:
  - "5.10.1"

branches:
  only:
    - master

before_install:
  - pip install --user codecov

before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install

cache:
  directories:
    - ./node_modules
    - ./vendor

notifications:
  email:
    on_success: never

script:
  - npm run test

after_success:
  - codecov --file results/lcov.info --disable search